Use a local Dangerfile instead of a remote one
I need to further investigate this, but it look to me like the kind of
Dangerfile one writer for Peril, which is async, doesn't work when
Danger reads it directly.

Below is the error we got. The build was
https://github.com/mokagio/WordPress-iOS/pull/9/checks?check_run_id=442490726#step:6:10

```
Unexpected token export
peril-downloaded-Automattic/peril-settings/org/pr/label.ts:3
export default async () => {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.requireFromString [as default] (/home/runner/work/WordPress-iOS/WordPress-iOS/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/runner/work/WordPress-iOS/WordPress-iOS/node_modules/danger/distribution/runner/runners/inline.js:144:63)
    at step (/home/runner/work/WordPress-iOS/WordPress-iOS/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/runner/work/WordPress-iOS/WordPress-iOS/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/runner/work/WordPress-iOS/WordPress-iOS/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/WordPress-iOS/WordPress-iOS/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at exports.runDangerfileEnvironment (/home/runner/work/WordPress-iOS/WordPress-iOS/node_modules/danger/distribution/runner/runners/inline.js:105:136)
    at Object.<anonymous> (/home/runner/work/WordPress-iOS/WordPress-iOS/node_modules/danger/distribution/platforms/GitHub.js:169:38)
```